from __future__ import annotations

from typing import TypedDict


class CountryEntry(TypedDict):
    code: str
    name: str


class CountryGroup(TypedDict):
    continent: str
    countries: tuple[CountryEntry, ...]


COUNTRY_GROUPS: tuple[CountryGroup, ...] = (
    {
        "continent": "Africa",
        "countries": (
            {"code": "DZ", "name": "Algeria"},
            {"code": "AO", "name": "Angola"},
            {"code": "BJ", "name": "Benin"},
            {"code": "BW", "name": "Botswana"},
            {"code": "IO", "name": "British Indian Ocean Territory"},
            {"code": "BF", "name": "Burkina Faso"},
            {"code": "BI", "name": "Burundi"},
            {"code": "CM", "name": "Cameroon"},
            {"code": "CV", "name": "Cape Verde"},
            {"code": "CF", "name": "Central African Republic"},
            {"code": "TD", "name": "Chad"},
            {"code": "KM", "name": "Comoros"},
            {"code": "CG", "name": "Congo - Brazzaville"},
            {"code": "CD", "name": "Congo - Kinshasa"},
            {"code": "CI", "name": "Côte d'Ivoire"},
            {"code": "DJ", "name": "Djibouti"},
            {"code": "EG", "name": "Egypt"},
            {"code": "GQ", "name": "Equatorial Guinea"},
            {"code": "ER", "name": "Eritrea"},
            {"code": "SZ", "name": "Eswatini"},
            {"code": "ET", "name": "Ethiopia"},
            {"code": "TF", "name": "French Southern Territories"},
            {"code": "GA", "name": "Gabon"},
            {"code": "GM", "name": "Gambia"},
            {"code": "GH", "name": "Ghana"},
            {"code": "GN", "name": "Guinea"},
            {"code": "GW", "name": "Guinea-Bissau"},
            {"code": "KE", "name": "Kenya"},
            {"code": "LS", "name": "Lesotho"},
            {"code": "LR", "name": "Liberia"},
            {"code": "LY", "name": "Libya"},
            {"code": "MG", "name": "Madagascar"},
            {"code": "MW", "name": "Malawi"},
            {"code": "MV", "name": "Maldives"},
            {"code": "ML", "name": "Mali"},
            {"code": "MR", "name": "Mauritania"},
            {"code": "MU", "name": "Mauritius"},
            {"code": "YT", "name": "Mayotte"},
            {"code": "MA", "name": "Morocco"},
            {"code": "MZ", "name": "Mozambique"},
            {"code": "NA", "name": "Namibia"},
            {"code": "NE", "name": "Niger"},
            {"code": "NG", "name": "Nigeria"},
            {"code": "RW", "name": "Rwanda"},
            {"code": "RE", "name": "Réunion"},
            {"code": "SN", "name": "Senegal"},
            {"code": "SC", "name": "Seychelles"},
            {"code": "SL", "name": "Sierra Leone"},
            {"code": "SO", "name": "Somalia"},
            {"code": "ZA", "name": "South Africa"},
            {"code": "SS", "name": "South Sudan"},
            {"code": "ES", "name": "Spain"},
            {"code": "SH", "name": "St. Helena"},
            {"code": "SD", "name": "Sudan"},
            {"code": "ST", "name": "São Tomé & Príncipe"},
            {"code": "TZ", "name": "Tanzania"},
            {"code": "TG", "name": "Togo"},
            {"code": "TN", "name": "Tunisia"},
            {"code": "UG", "name": "Uganda"},
            {"code": "EH", "name": "Western Sahara"},
            {"code": "ZM", "name": "Zambia"},
            {"code": "ZW", "name": "Zimbabwe"},
        ),
    },
    {
        "continent": "Antarctica",
        "countries": (
            {"code": "AQ", "name": "Antarctica"},
            {"code": "BV", "name": "Bouvet Island"},
            {"code": "HM", "name": "Heard & McDonald Islands"},
        ),
    },
    {
        "continent": "Asia",
        "countries": (
            {"code": "AF", "name": "Afghanistan"},
            {"code": "AM", "name": "Armenia"},
            {"code": "AZ", "name": "Azerbaijan"},
            {"code": "BH", "name": "Bahrain"},
            {"code": "BD", "name": "Bangladesh"},
            {"code": "BT", "name": "Bhutan"},
            {"code": "BN", "name": "Brunei"},
            {"code": "KH", "name": "Cambodia"},
            {"code": "CN", "name": "China"},
            {"code": "CX", "name": "Christmas Island"},
            {"code": "CC", "name": "Cocos (Keeling) Islands"},
            {"code": "GE", "name": "Georgia"},
            {"code": "HK", "name": "Hong Kong SAR China"},
            {"code": "IS", "name": "Iceland"},
            {"code": "IN", "name": "India"},
            {"code": "ID", "name": "Indonesia"},
            {"code": "IR", "name": "Iran"},
            {"code": "IQ", "name": "Iraq"},
            {"code": "IL", "name": "Israel"},
            {"code": "JP", "name": "Japan"},
            {"code": "JO", "name": "Jordan"},
            {"code": "KZ", "name": "Kazakhstan"},
            {"code": "KW", "name": "Kuwait"},
            {"code": "KG", "name": "Kyrgyzstan"},
            {"code": "LA", "name": "Laos"},
            {"code": "LB", "name": "Lebanon"},
            {"code": "MO", "name": "Macao SAR China"},
            {"code": "MY", "name": "Malaysia"},
            {"code": "MN", "name": "Mongolia"},
            {"code": "MM", "name": "Myanmar (Burma)"},
            {"code": "NP", "name": "Nepal"},
            {"code": "KP", "name": "North Korea"},
            {"code": "OM", "name": "Oman"},
            {"code": "PK", "name": "Pakistan"},
            {"code": "PS", "name": "Palestinian Territories"},
            {"code": "PH", "name": "Philippines"},
            {"code": "PT", "name": "Portugal"},
            {"code": "QA", "name": "Qatar"},
            {"code": "SA", "name": "Saudi Arabia"},
            {"code": "SG", "name": "Singapore"},
            {"code": "KR", "name": "South Korea"},
            {"code": "LK", "name": "Sri Lanka"},
            {"code": "SY", "name": "Syria"},
            {"code": "TW", "name": "Taiwan"},
            {"code": "TJ", "name": "Tajikistan"},
            {"code": "TH", "name": "Thailand"},
            {"code": "TL", "name": "Timor-Leste"},
            {"code": "TM", "name": "Turkmenistan"},
            {"code": "AE", "name": "United Arab Emirates"},
            {"code": "UZ", "name": "Uzbekistan"},
            {"code": "VN", "name": "Vietnam"},
            {"code": "YE", "name": "Yemen"},
        ),
    },
    {
        "continent": "Europe",
        "countries": (
            {"code": "AL", "name": "Albania"},
            {"code": "AD", "name": "Andorra"},
            {"code": "AT", "name": "Austria"},
            {"code": "BY", "name": "Belarus"},
            {"code": "BE", "name": "Belgium"},
            {"code": "BA", "name": "Bosnia & Herzegovina"},
            {"code": "BG", "name": "Bulgaria"},
            {"code": "HR", "name": "Croatia"},
            {"code": "CY", "name": "Cyprus"},
            {"code": "CZ", "name": "Czechia"},
            {"code": "DK", "name": "Denmark"},
            {"code": "EE", "name": "Estonia"},
            {"code": "FO", "name": "Faroe Islands"},
            {"code": "FI", "name": "Finland"},
            {"code": "FR", "name": "France"},
            {"code": "DE", "name": "Germany"},
            {"code": "GI", "name": "Gibraltar"},
            {"code": "GR", "name": "Greece"},
            {"code": "GG", "name": "Guernsey"},
            {"code": "HU", "name": "Hungary"},
            {"code": "IE", "name": "Ireland"},
            {"code": "IM", "name": "Isle of Man"},
            {"code": "IT", "name": "Italy"},
            {"code": "JE", "name": "Jersey"},
            {"code": "LV", "name": "Latvia"},
            {"code": "LI", "name": "Liechtenstein"},
            {"code": "LT", "name": "Lithuania"},
            {"code": "LU", "name": "Luxembourg"},
            {"code": "MT", "name": "Malta"},
            {"code": "MD", "name": "Moldova"},
            {"code": "MC", "name": "Monaco"},
            {"code": "ME", "name": "Montenegro"},
            {"code": "NL", "name": "Netherlands"},
            {"code": "MK", "name": "North Macedonia"},
            {"code": "NO", "name": "Norway"},
            {"code": "PL", "name": "Poland"},
            {"code": "RO", "name": "Romania"},
            {"code": "RU", "name": "Russia"},
            {"code": "SM", "name": "San Marino"},
            {"code": "RS", "name": "Serbia"},
            {"code": "SK", "name": "Slovakia"},
            {"code": "SI", "name": "Slovenia"},
            {"code": "SJ", "name": "Svalbard & Jan Mayen"},
            {"code": "SE", "name": "Sweden"},
            {"code": "CH", "name": "Switzerland"},
            {"code": "TR", "name": "Türkiye"},
            {"code": "UA", "name": "Ukraine"},
            {"code": "GB", "name": "United Kingdom"},
            {"code": "VA", "name": "Vatican City"},
            {"code": "AX", "name": "Åland Islands"},
        ),
    },
    {
        "continent": "North America",
        "countries": (
            {"code": "AI", "name": "Anguilla"},
            {"code": "AG", "name": "Antigua & Barbuda"},
            {"code": "AW", "name": "Aruba"},
            {"code": "BS", "name": "Bahamas"},
            {"code": "BB", "name": "Barbados"},
            {"code": "BZ", "name": "Belize"},
            {"code": "BM", "name": "Bermuda"},
            {"code": "VG", "name": "British Virgin Islands"},
            {"code": "CA", "name": "Canada"},
            {"code": "BQ", "name": "Caribbean Netherlands"},
            {"code": "KY", "name": "Cayman Islands"},
            {"code": "CR", "name": "Costa Rica"},
            {"code": "CU", "name": "Cuba"},
            {"code": "CW", "name": "Curaçao"},
            {"code": "DM", "name": "Dominica"},
            {"code": "DO", "name": "Dominican Republic"},
            {"code": "SV", "name": "El Salvador"},
            {"code": "GL", "name": "Greenland"},
            {"code": "GD", "name": "Grenada"},
            {"code": "GP", "name": "Guadeloupe"},
            {"code": "GT", "name": "Guatemala"},
            {"code": "HT", "name": "Haiti"},
            {"code": "HN", "name": "Honduras"},
            {"code": "JM", "name": "Jamaica"},
            {"code": "MQ", "name": "Martinique"},
            {"code": "MX", "name": "Mexico"},
            {"code": "MS", "name": "Montserrat"},
            {"code": "NI", "name": "Nicaragua"},
            {"code": "PA", "name": "Panama"},
            {"code": "PR", "name": "Puerto Rico"},
            {"code": "SX", "name": "Sint Maarten"},
            {"code": "BL", "name": "St. Barthélemy"},
            {"code": "KN", "name": "St. Kitts & Nevis"},
            {"code": "LC", "name": "St. Lucia"},
            {"code": "MF", "name": "St. Martin"},
            {"code": "PM", "name": "St. Pierre & Miquelon"},
            {"code": "VC", "name": "St. Vincent & Grenadines"},
            {"code": "TT", "name": "Trinidad & Tobago"},
            {"code": "TC", "name": "Turks & Caicos Islands"},
            {"code": "VI", "name": "U.S. Virgin Islands"},
            {"code": "US", "name": "United States"},
        ),
    },
    {
        "continent": "Oceania",
        "countries": (
            {"code": "AS", "name": "American Samoa"},
            {"code": "AU", "name": "Australia"},
            {"code": "CK", "name": "Cook Islands"},
            {"code": "FJ", "name": "Fiji"},
            {"code": "PF", "name": "French Polynesia"},
            {"code": "GU", "name": "Guam"},
            {"code": "KI", "name": "Kiribati"},
            {"code": "MH", "name": "Marshall Islands"},
            {"code": "FM", "name": "Micronesia"},
            {"code": "NR", "name": "Nauru"},
            {"code": "NC", "name": "New Caledonia"},
            {"code": "NZ", "name": "New Zealand"},
            {"code": "NU", "name": "Niue"},
            {"code": "NF", "name": "Norfolk Island"},
            {"code": "MP", "name": "Northern Mariana Islands"},
            {"code": "PW", "name": "Palau"},
            {"code": "PG", "name": "Papua New Guinea"},
            {"code": "PN", "name": "Pitcairn Islands"},
            {"code": "WS", "name": "Samoa"},
            {"code": "SB", "name": "Solomon Islands"},
            {"code": "TK", "name": "Tokelau"},
            {"code": "TO", "name": "Tonga"},
            {"code": "TV", "name": "Tuvalu"},
            {"code": "UM", "name": "U.S. Outlying Islands"},
            {"code": "VU", "name": "Vanuatu"},
            {"code": "WF", "name": "Wallis & Futuna"},
        ),
    },
    {
        "continent": "South America",
        "countries": (
            {"code": "AR", "name": "Argentina"},
            {"code": "BO", "name": "Bolivia"},
            {"code": "BR", "name": "Brazil"},
            {"code": "CL", "name": "Chile"},
            {"code": "CO", "name": "Colombia"},
            {"code": "EC", "name": "Ecuador"},
            {"code": "FK", "name": "Falkland Islands"},
            {"code": "GF", "name": "French Guiana"},
            {"code": "GY", "name": "Guyana"},
            {"code": "PY", "name": "Paraguay"},
            {"code": "PE", "name": "Peru"},
            {"code": "GS", "name": "South Georgia & South Sandwich Islands"},
            {"code": "SR", "name": "Suriname"},
            {"code": "UY", "name": "Uruguay"},
            {"code": "VE", "name": "Venezuela"},
        ),
    },
)


class CountryCatalog:
    @staticmethod
    def groups_as_dict() -> dict[str, object]:
        return {
            "items": [
                {
                    "continent": str(group["continent"]),
                    "countries": [dict(country) for country in group["countries"]],
                }
                for group in COUNTRY_GROUPS
            ]
        }

    @staticmethod
    def options() -> tuple[dict[str, str], ...]:
        return tuple(
            {
                "value": str(country["code"]),
                "label": str(country["name"]),
                "group": str(group["continent"]),
            }
            for group in COUNTRY_GROUPS
            for country in group["countries"]
        )

    @staticmethod
    def options_as_dict() -> dict[str, object]:
        return {"items": [dict(option) for option in CountryCatalog.options()]}
