@startuml
component "OpenInfra APIs" as API
component "PgBouncer" as PGB
component "HAProxy" as HAP
database "PostgreSQL Primary" as P
Database "Replica 1" as R1
Database "Replica 2" as R2
cloud "WAL Archive / S3" as WAL
component "pgBackRest" as B
API --> PGB
PGB --> HAP
HAP --> P : writes
HAP --> R1 : reads
HAP --> R2 : reads
P --> R1 : streaming replication
P --> R2 : streaming replication
P --> WAL : WAL
B --> WAL : backups/PITR
@enduml
