BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS ip_aggregates (
    id uuid NOT NULL,
    tenant_id text NOT NULL REFERENCES tenants(id),
    vrf_name text NOT NULL,
    cidr cidr NOT NULL,
    family smallint NOT NULL,
    description text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, vrf_name, cidr),
    CHECK (family IN (4, 6))
) PARTITION BY HASH (tenant_id);
CREATE TABLE IF NOT EXISTS ip_aggregates_p00 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS ip_aggregates_p01 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS ip_aggregates_p02 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS ip_aggregates_p03 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS ip_aggregates_p04 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS ip_aggregates_p05 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS ip_aggregates_p06 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS ip_aggregates_p07 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS ip_aggregates_p08 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS ip_aggregates_p09 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS ip_aggregates_p10 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS ip_aggregates_p11 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS ip_aggregates_p12 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS ip_aggregates_p13 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS ip_aggregates_p14 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS ip_aggregates_p15 PARTITION OF ip_aggregates FOR VALUES WITH (MODULUS 16, REMAINDER 15);

CREATE TABLE IF NOT EXISTS ip_ranges (
    id uuid NOT NULL,
    tenant_id text NOT NULL REFERENCES tenants(id),
    vrf_name text NOT NULL,
    prefix_cidr cidr NOT NULL,
    start_address inet NOT NULL,
    end_address inet NOT NULL,
    purpose text NOT NULL,
    description text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, vrf_name, prefix_cidr, start_address, end_address),
    CHECK (purpose IN ('allocation', 'reservation', 'exclusion')),
    CHECK (family(start_address) = family(end_address)),
    CHECK (start_address <= end_address)
) PARTITION BY HASH (tenant_id);
CREATE TABLE IF NOT EXISTS ip_ranges_p00 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 0);
CREATE TABLE IF NOT EXISTS ip_ranges_p01 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 1);
CREATE TABLE IF NOT EXISTS ip_ranges_p02 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 2);
CREATE TABLE IF NOT EXISTS ip_ranges_p03 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 3);
CREATE TABLE IF NOT EXISTS ip_ranges_p04 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 4);
CREATE TABLE IF NOT EXISTS ip_ranges_p05 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 5);
CREATE TABLE IF NOT EXISTS ip_ranges_p06 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 6);
CREATE TABLE IF NOT EXISTS ip_ranges_p07 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 7);
CREATE TABLE IF NOT EXISTS ip_ranges_p08 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 8);
CREATE TABLE IF NOT EXISTS ip_ranges_p09 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 9);
CREATE TABLE IF NOT EXISTS ip_ranges_p10 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 10);
CREATE TABLE IF NOT EXISTS ip_ranges_p11 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 11);
CREATE TABLE IF NOT EXISTS ip_ranges_p12 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 12);
CREATE TABLE IF NOT EXISTS ip_ranges_p13 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 13);
CREATE TABLE IF NOT EXISTS ip_ranges_p14 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 14);
CREATE TABLE IF NOT EXISTS ip_ranges_p15 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 15);
CREATE TABLE IF NOT EXISTS ip_ranges_p16 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 16);
CREATE TABLE IF NOT EXISTS ip_ranges_p17 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 17);
CREATE TABLE IF NOT EXISTS ip_ranges_p18 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 18);
CREATE TABLE IF NOT EXISTS ip_ranges_p19 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 19);
CREATE TABLE IF NOT EXISTS ip_ranges_p20 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 20);
CREATE TABLE IF NOT EXISTS ip_ranges_p21 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 21);
CREATE TABLE IF NOT EXISTS ip_ranges_p22 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 22);
CREATE TABLE IF NOT EXISTS ip_ranges_p23 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 23);
CREATE TABLE IF NOT EXISTS ip_ranges_p24 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 24);
CREATE TABLE IF NOT EXISTS ip_ranges_p25 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 25);
CREATE TABLE IF NOT EXISTS ip_ranges_p26 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 26);
CREATE TABLE IF NOT EXISTS ip_ranges_p27 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 27);
CREATE TABLE IF NOT EXISTS ip_ranges_p28 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 28);
CREATE TABLE IF NOT EXISTS ip_ranges_p29 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 29);
CREATE TABLE IF NOT EXISTS ip_ranges_p30 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 30);
CREATE TABLE IF NOT EXISTS ip_ranges_p31 PARTITION OF ip_ranges FOR VALUES WITH (MODULUS 32, REMAINDER 31);

CREATE TABLE IF NOT EXISTS ip_address_records (
    id uuid NOT NULL,
    tenant_id text NOT NULL REFERENCES tenants(id),
    vrf_name text NOT NULL,
    prefix_cidr cidr NOT NULL,
    address inet NOT NULL,
    hostname text NOT NULL,
    interface_name text,
    status text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, vrf_name, address),
    CHECK (status IN ('planned', 'reserved', 'active', 'deprecated'))
) PARTITION BY HASH (tenant_id);
CREATE TABLE IF NOT EXISTS ip_address_records_p00 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 0);
CREATE TABLE IF NOT EXISTS ip_address_records_p01 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 1);
CREATE TABLE IF NOT EXISTS ip_address_records_p02 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 2);
CREATE TABLE IF NOT EXISTS ip_address_records_p03 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 3);
CREATE TABLE IF NOT EXISTS ip_address_records_p04 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 4);
CREATE TABLE IF NOT EXISTS ip_address_records_p05 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 5);
CREATE TABLE IF NOT EXISTS ip_address_records_p06 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 6);
CREATE TABLE IF NOT EXISTS ip_address_records_p07 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 7);
CREATE TABLE IF NOT EXISTS ip_address_records_p08 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 8);
CREATE TABLE IF NOT EXISTS ip_address_records_p09 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 9);
CREATE TABLE IF NOT EXISTS ip_address_records_p10 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 10);
CREATE TABLE IF NOT EXISTS ip_address_records_p11 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 11);
CREATE TABLE IF NOT EXISTS ip_address_records_p12 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 12);
CREATE TABLE IF NOT EXISTS ip_address_records_p13 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 13);
CREATE TABLE IF NOT EXISTS ip_address_records_p14 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 14);
CREATE TABLE IF NOT EXISTS ip_address_records_p15 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 15);
CREATE TABLE IF NOT EXISTS ip_address_records_p16 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 16);
CREATE TABLE IF NOT EXISTS ip_address_records_p17 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 17);
CREATE TABLE IF NOT EXISTS ip_address_records_p18 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 18);
CREATE TABLE IF NOT EXISTS ip_address_records_p19 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 19);
CREATE TABLE IF NOT EXISTS ip_address_records_p20 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 20);
CREATE TABLE IF NOT EXISTS ip_address_records_p21 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 21);
CREATE TABLE IF NOT EXISTS ip_address_records_p22 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 22);
CREATE TABLE IF NOT EXISTS ip_address_records_p23 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 23);
CREATE TABLE IF NOT EXISTS ip_address_records_p24 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 24);
CREATE TABLE IF NOT EXISTS ip_address_records_p25 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 25);
CREATE TABLE IF NOT EXISTS ip_address_records_p26 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 26);
CREATE TABLE IF NOT EXISTS ip_address_records_p27 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 27);
CREATE TABLE IF NOT EXISTS ip_address_records_p28 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 28);
CREATE TABLE IF NOT EXISTS ip_address_records_p29 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 29);
CREATE TABLE IF NOT EXISTS ip_address_records_p30 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 30);
CREATE TABLE IF NOT EXISTS ip_address_records_p31 PARTITION OF ip_address_records FOR VALUES WITH (MODULUS 32, REMAINDER 31);

CREATE INDEX IF NOT EXISTS idx_ip_aggregates_vrf_family ON ip_aggregates (tenant_id, vrf_name, family, cidr);
CREATE INDEX IF NOT EXISTS idx_prefixes_vrf_family ON prefixes (tenant_id, vrf_name, family, cidr);
CREATE INDEX IF NOT EXISTS idx_ip_ranges_lookup ON ip_ranges (tenant_id, vrf_name, prefix_cidr, start_address, end_address);
CREATE INDEX IF NOT EXISTS idx_ip_address_records_lookup ON ip_address_records (tenant_id, vrf_name, prefix_cidr, address);
CREATE INDEX IF NOT EXISTS idx_ipam_audit_events ON audit_events (tenant_id, action, created_at DESC) WHERE action LIKE 'ipam.%';

COMMIT;
